### ISSUE TITLE
Template headers to be Added

### ISSUE THREAD

**Issue by Shannyn85** [kingram6865/shannyn#1]
Home
About
Process
Pricing
Services
Contact

**Comment by kingram6865** [comment]
Select the "Website" option
![Image](https://github.com/kingram6865/shannyn/assets/13263318/228d482a-98cd-4555-aea9-b13d5eea1ad2)

The "Main Navigation" section is where we add, remove or edit the page titles
![Image](https://github.com/kingram6865/shannyn/assets/13263318/2e008441-a608-4913-8ca4-e099031f83dc)

These navigation headings were changed on 2024 01 14 1500 PST

Also, the navigation headings can be re-ordered by selecting and then dragging them to any desired position.
