### ISSUE TITLE
Content for  About page

### ISSUE THREAD

**Issue by Shannyn85** [kingram6865/shannyn#2]
About the owner:
Shannyn was born and raised in the Bay Area. She has a Bachelor’s in Nursing and loves that work but organizing is her passion. The skills she has developed in the medical field have uniquely positioned her well in the industry of professional organizing as she has a keen sense of the most intimate and vulnerable contributions leading to the needs of her support for her clients. Sure, she can come in and move your things around and make it look pretty (which she is so willing to do) but it’s her skills in helping her clients feel at ease as she moves through their personal space and how she supports them through the often difficult choices that arise through this process that make her special.

**Comment by Shannyn85** [comment]
The content I want used on the about page is highlighted and noted

**Comment by kingram6865** [comment]
Text added.
